api/urls.py
from django.urls import path

from api.views import StudentListCreateApiView, StudentDetailUpdateDeleteApiView

urlpatterns = [
    path("students/", StudentListCreateApiView.as_view(), name="students_create_list_api"),
    path("student/<int:pk>", StudentDetailUpdateDeleteApiView.as_view(), name="student_detail_update_delete_api"),
]

collegeProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
    path('api/', include('api.urls'))
]

students/urls.py
from django.urls import path

from students.views import StudentsListView, StudentDetailView, StudentCreateView, StudentDeleteView, StudentUpdateView

urlpatterns = [
    path("students/", StudentsListView.as_view(), name="students_list"),
    path("student/<int:pk>/", StudentDetailView.as_view(), name="student_detail"),
    path("student/create/", StudentCreateView.as_view(), name="student_create"),
    path("student/<int:pk>/delete", StudentDeleteView.as_view(), name="student_delete"),
    path("student/<int:pk>/update", StudentUpdateView.as_view(), name="student_update")
]

api/models.py
from django.db import models

# Create your models here.

students/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Student(models.Model):
    reg_no = models.BigIntegerField()
    name = models.CharField(max_length=250)
    email = models.EmailField()
    department = models.CharField(max_length=100)
    dob = models.DateField()
    joined_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.department}"

    def get_absolute_url(self):
        return reverse('students_list')

api/views.py
from django.shortcuts import render
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView

from students.models import Student
from .serializers import StudentSerializer


# Create your views here.
class StudentListCreateApiView(ListCreateAPIView):
    queryset = Student.objects.all()    # gets all rows from the table
    serializer_class = StudentSerializer


class StudentDetailUpdateDeleteApiView(RetrieveUpdateDestroyAPIView):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer

students/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Student


# Create your views here.

class StudentsListView(ListView):
    model = Student
    template_name = "students.html"


class StudentDetailView(DetailView):
    model = Student
    template_name = "student_detail.html"


class StudentCreateView(CreateView):
    model = Student
    template_name = "student_create.html"
    fields = "__all__"


class StudentDeleteView(DeleteView):
    model = Student
    template_name = "student_delete.html"
    success_url = reverse_lazy('students_list')


class StudentUpdateView(UpdateView):
    model = Student
    template_name = "student_update.html"
    fields = "__all__"

templates/student_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Student</title>
</head>
<body>

  <form action="" method="post">
      {% csrf_token %}
    {{ form.as_p }}
      <input type="submit" value="Create Student">
  </form>

</body>
</html>

templates/student_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Student</title>
</head>
<body>
  <form action="" method="post">
      {% csrf_token %}
    <p>Are you sure you want to delete the entry?</p>
    <input type="submit" value="Confirm Delete">
  </form>
</body>
</html>

templates/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ student.name }}</title>
</head>
<body>
  <ul>
    <li>
        <p>Name: {{ student.name }}</p>
        <p>Department: {{ student.department }}</p>
        <p>Email: {{ student.email }}</p>
        <p>Register Number: {{ student.reg_no }}</p>
        <p>Date of Birth: {{ student.dob }}</p>
        <p>Joining Date: {{ student.joined_date }}</p>
    </li>
  </ul>

    <button><a href="{% url 'student_delete' student.pk %}">Delete Student</a></button>
    <button><a href="{% url 'student_update' student.pk %}">Update Student</a></button>
</body>
</html>

templates/student_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Student</title>
</head>
<body>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Student">
  </form>
</body>
</html>

templates/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Students</title>
</head>
<body>
    <ul>
        {% for student in student_list %}
            <a href="{% url 'student_detail' student.pk %}"> <li>{{student.name}}</li> </a>
        {% endfor%}
    </ul>

    <button><a href="{% url 'student_create' %}">Create Student</a></button>

</body>
</html>